FROM jenkins/jenkins
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# Install plugins includin JCasC
COPY jenkins-plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Set JCasC configuration
COPY configuration.yaml /var/jenkins_home/configuration.yaml
ENV CASC_JENKINS_CONFIG /var/jenkins_home/configuration.yaml